### ISSUE TITLE
Document need to run `init` better

### ISSUE THREAD

**Issue by tv42** [lucacasonato/ammonia-wasm#1]
Please document the need to run `init` better.

Readme has it in the example, but that's very easy to skip.

Especially, if like me, you were reading https://doc.deno.land/https://deno.land/x/ammonia@0.3.1/mod.ts in the first place.

```
$ deno --version
deno 1.22.0 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.17
typescript 4.6.2
$ deno eval 'import {clean} from "https://deno.land/x/ammonia@0.3.1/mod.ts"; const input = "foo"; const output = clean(input); console.log({output});'
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
        wasm.__wbindgen_add_to_stack_pointer(16);
             ^
    at clean (https://deno.land/x/ammonia@0.3.1/pkg/ammonia_wasm.js:116:14)
    at clean (https://deno.land/x/ammonia@0.3.1/mod.ts:38:10)
    at file:///tmp/$deno$eval.js:1:101
```

**Comment by tv42** [comment]
Nevermind, I didn't run `init`. Retitling to ask for better docs and error message.
